import turtle
tur= turtle.Screen()
turtle.bgcolor("blue")
turtle.color("black","orange")
turtle.up()
turtle.setposition(-200,100)
turtle.down()
turtle.begin_fill()
turtle.circle(80)
turtle.end_fill()
turtle.color("black","white")
turtle.up()
turtle.setposition(-200,-70)
turtle.down()
turtle.begin_fill()
turtle.circle(80)
turtle.end_fill()
turtle.color("black","green")
turtle.up()
turtle.setposition(-200,-250)
turtle.down()
turtle.begin_fill()
turtle.circle(80)
turtle.end_fill()
turtle.penup()
turtle.setposition(0,-70)
turtle.pendown()
turtle.write("\n Happy \n Rebublic \n Day!", font= ("Helvetica", 50, "bold"))
turtle.done()
